[build]
	command = "gatsby build"
	publish = "public"
  base = "."
[dev]
	command = "gatsby develop"
[[headers]]
  for = "*/"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"